@extends('layouts.app')
@section('title', 'Purchase Summary')
@section('content')
<div class="page-wrapper"><div class="content"><div class="page-header"><div class="page-title"><h4>Purchase Summary</h4></div></div>
@include('tenant.reports.partials.filters', ['showTerminal' => false, 'showOrderType' => false, 'showCsvExport' => true])
@php $t = $totals; @endphp
<div class="row g-3 mb-3"><div class="col-md-2"><div class="card border-0 shadow-sm text-center"><div class="card-body py-2"><div class="text-muted small">Bills</div><h5 class="fw-bold">{{ number_format($t['bill_count']) }}</h5></div></div></div><div class="col-md-2"><div class="card border-0 shadow-sm text-center"><div class="card-body py-2"><div class="text-muted small">Subtotal</div><h5 class="fw-bold">{{ number_format($t['total_subtotal'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card border-0 shadow-sm text-center"><div class="card-body py-2"><div class="text-muted small">Tax</div><h5 class="fw-bold">{{ number_format($t['total_tax'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card border-0 shadow-sm text-center"><div class="card-body py-2"><div class="text-muted small">Grand Total</div><h5 class="fw-bold">{{ number_format($t['total_grand'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card border-0 shadow-sm text-center"><div class="card-body py-2"><div class="text-muted small">Paid</div><h5 class="fw-bold">{{ number_format($t['total_paid'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card border-0 shadow-sm text-center"><div class="card-body py-2"><div class="text-muted small">Outstanding</div><h5 class="fw-bold text-warning">{{ number_format($t['total_balance'], 2) }}</h5></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-0"><table class="table table-sm mb-0"><caption class="visually-hidden">Purchase bills</caption><thead class="table-light"><tr><th scope="col">Bill No</th><th scope="col">Date</th><th scope="col">Supplier</th><th scope="col">Branch</th><th scope="col" class="text-end">Grand Total</th><th scope="col" class="text-end">Paid</th><th scope="col" class="text-end">Balance</th><th scope="col">Status</th></tr></thead><tbody>@forelse($bills as $b)<tr><td><code>{{ $b->bill_no }}</code></td><td>{{ $b->bill_date->format('d/m/Y') }}</td><td>{{ $b->supplier?->name }}</td><td>{{ $b->branch?->name }}</td><td class="text-end">{{ number_format($b->grand_total, 2) }}</td><td class="text-end">{{ number_format($b->amount_paid, 2) }}</td><td class="text-end">{{ number_format($b->balance_due, 2) }}</td><td><span class="badge bg-secondary small">{{ ucfirst($b->status) }}</span></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No bills in range.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $bills->links() }}</div></div></div></div>
@endsection
