@extends('layouts.app')

@section('title', 'Adjustment ' . $stockAdjustment->adjustment_no)

@section('content')
<div class="d-flex align-items-center justify-content-between flex-wrap gap-3 mb-4">
    <div>
        <h1 class="mb-1">{{ $stockAdjustment->adjustment_no }}</h1>
        <p class="fw-medium text-muted mb-0">
            {{ ucfirst($stockAdjustment->adjustment_type) }} &middot;
            {{ $stockAdjustment->adjustment_date->format('d M Y') }} &middot;
            {{ $stockAdjustment->branch?->name }}
        </p>
    </div>
    <a href="{{ url('/stock-adjustments') }}" class="btn btn-light">Back</a>
</div>

<div class="row g-3 mb-4">
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-header"><strong>Details</strong></div>
            <div class="card-body">
                <dl class="row mb-0">
                    <dt class="col-sm-4">Status</dt>
                    <dd class="col-sm-8">
                        <span class="badge bg-{{ $stockAdjustment->status === 'posted' ? 'success' : 'secondary' }}">
                            {{ ucfirst($stockAdjustment->status) }}
                        </span>
                    </dd>
                    <dt class="col-sm-4">Posted By</dt>
                    <dd class="col-sm-8">{{ $stockAdjustment->postedBy?->name ?? '—' }}</dd>
                    <dt class="col-sm-4">Posted At</dt>
                    <dd class="col-sm-8">{{ $stockAdjustment->posted_at?->format('d M Y H:i') ?? '—' }}</dd>
                    @if($stockAdjustment->notes)
                    <dt class="col-sm-4">Notes</dt>
                    <dd class="col-sm-8">{{ $stockAdjustment->notes }}</dd>
                    @endif
                </dl>
            </div>
        </div>
    </div>
</div>

{{-- Lines --}}
<div class="card mb-4">
    <div class="card-header"><strong>Adjustment Lines</strong></div>
    <div class="card-body table-responsive p-0">
        <table class="table table-nowrap align-middle mb-0">
            <caption class="visually-hidden">Stock adjustment lines</caption>
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Variant</th>
                    <th scope="col">Batch No</th>
                    <th scope="col">Expiry</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Unit Cost</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
            @foreach($stockAdjustment->lines as $line)
                <tr>
                    <td>
                        <code>{{ $line->product?->sku }}</code><br>
                        <small>{{ $line->product?->name }}</small>
                    </td>
                    <td>{{ $line->variant?->name ?? '—' }}</td>
                    <td>{{ $line->batch_no ?? '—' }}</td>
                    <td>{{ $line->expiry_date?->format('d M Y') ?? '—' }}</td>
                    <td>{{ number_format($line->quantity, 3) }}</td>
                    <td>{{ number_format($line->unit_cost, 4) }}</td>
                    <td>{{ number_format($line->quantity * $line->unit_cost, 2) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

{{-- Ledger --}}
<div class="card">
    <div class="card-header"><strong>Ledger Entries</strong></div>
    <div class="card-body table-responsive p-0">
        <table class="table table-nowrap align-middle mb-0">
            <caption class="visually-hidden">Ledger entries generated by this adjustment</caption>
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Movement</th>
                    <th scope="col">Direction</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Unit Cost</th>
                    <th scope="col">Balance After</th>
                </tr>
            </thead>
            <tbody>
            @forelse($ledgers as $ledger)
                <tr>
                    <td>{{ $ledger->product?->name }}</td>
                    <td><span class="badge bg-light text-dark">{{ str_replace('_', ' ', ucfirst($ledger->movement_type)) }}</span></td>
                    <td>
                        <span class="badge bg-{{ $ledger->direction === 'in' ? 'success' : 'danger' }}">
                            {{ ucfirst($ledger->direction) }}
                        </span>
                    </td>
                    <td>{{ number_format($ledger->quantity, 3) }}</td>
                    <td>{{ number_format($ledger->unit_cost, 4) }}</td>
                    <td>{{ number_format($ledger->balance_after, 3) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center text-muted py-3">No ledger entries.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection
