<?php

namespace App\Support\Edge;

use Illuminate\Support\Str;

/**
 * EDGE-IDENTITY-1 — the canonical CROSS-SYSTEM identity contract.
 *
 * Cloud and Branch Server (Edge) databases have DIFFERENT numeric primary keys. A sale that is `id=17`
 * on an Edge appliance may be `id=901` once ingested into Cloud. Numeric ids are therefore LOCAL ONLY —
 * they are never the identity by which two systems agree "this is the same business object".
 *
 * Every sync-relevant operational entity carries a durable, immutable, globally-unique application
 * identity generated at creation time and NEVER regenerated. This class is the single source of truth for
 * WHICH column holds that identity per entity and WHICH format it uses. The identity lives on the business
 * row itself (no polymorphic identity table); models opt in via {@see \App\Models\Concerns\HasCanonicalIdentity}.
 *
 * Format decision (locked): NEW identities use **ULID** (26 chars) to match the already-canonical
 * `shifts.shift_uuid` and the locked offline `SO-{branch}-{terminal}-{ULID}` sale-number design.
 * Two PRE-EXISTING canonical identities — `kot_batches.event_uuid` and
 * `sales_order_line_cancellations.event_uuid` — remain **UUID v4**: they were shipped earlier, are already
 * unique+immutable in practice, and the print `logical_key` strings are derived from them, so converting
 * them would break the deployed print-idempotency contract. That is the one documented format exception.
 *
 * Display numbers (`sale_no`, `session_no`, `approval_no`, KOT `#N`, `job_no`, receipt no) are HUMAN labels,
 * NOT identities — never synchronise objects by them. Idempotency tokens (`sales_orders.client_uuid`,
 * `print_jobs.logical_key`) dedup a single write; they are NOT the object identity either.
 */
final class EdgeIdentity
{
    public const FORMAT_ULID = 'ulid';
    public const FORMAT_UUID = 'uuid';

    /**
     * Canonical identity registry: model FQCN => [column, format].
     *
     * Entities the {@see \App\Models\Concerns\HasCanonicalIdentity} trait manages (generate-on-create +
     * immutable). The three "reused" identities below are listed for documentation/validation only — they
     * are generated by their own existing model hooks and must not be double-managed here.
     */
    public const REGISTRY = [
        \App\Models\Tenant\SalesOrder::class             => ['sale_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\SalesOrderLine::class         => ['line_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\SalePayment::class            => ['payment_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\KotBatchLine::class           => ['kot_line_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\RestaurantTableSession::class => ['session_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\ManagerApproval::class        => ['approval_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\Customer::class               => ['customer_uuid', self::FORMAT_ULID],
    ];

    /** Reused, pre-existing canonical identities (own generation hooks; documented, not trait-managed). */
    public const REUSED = [
        \App\Models\Tenant\Shift::class                        => ['shift_uuid', self::FORMAT_ULID],
        \App\Models\Tenant\KotBatch::class                     => ['event_uuid', self::FORMAT_UUID],
        \App\Models\Tenant\SalesOrderLineCancellation::class   => ['event_uuid', self::FORMAT_UUID],
    ];

    /** Generate a fresh canonical identity in the requested format. */
    public static function generate(string $format): string
    {
        return $format === self::FORMAT_UUID ? (string) Str::uuid() : (string) Str::ulid();
    }

    /** Validate a value against the given canonical format. */
    public static function isValid(?string $value, string $format): bool
    {
        if ($value === null || $value === '') {
            return false;
        }

        return $format === self::FORMAT_UUID ? Str::isUuid($value) : Str::isUlid($value);
    }

    /** The [column, format] pair for a managed model, or null if it is not registered. */
    public static function for(string $modelClass): ?array
    {
        return self::REGISTRY[$modelClass] ?? null;
    }
}
