<!DOCTYPE html>
<html lang="en">
<body style="font-family: Arial, sans-serif; color: #1a1a1a">
<h2 style="margin-bottom: 4px">{{ $businessName }}</h2>
<p style="margin-top: 0">Sales report for <strong>{{ $periodLabel }}</strong>.</p>
<p>
    @if($pdfContent !== null)
        Your complete A4 Sales Report Centre report is attached as a PDF.
    @else
        The selected report sections are attached as CSV files (Excel-compatible).
    @endif
</p>
<ul>
    @foreach($reportSections ?: array_keys($csvSections) as $section)
        <li>{{ ucwords(str_replace('_', ' ', $section)) }}</li>
    @endforeach
</ul>
<p style="color: #667; font-size: 12px">
    Sales reports answer “what did we sell?”. The Cash &amp; Bank Movement section answers “where did
    money come from and where did it go?” — opening floats and transfers are never counted as revenue.
</p>
<p style="color: #99a; font-size: 11px">Generated by Bingoo POS at {{ now()->toDateTimeString() }} (server time).</p>
</body>
</html>
